apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: slsa-demo-releaseplan
  namespace: tenant-namespace
  labels:
    app.kubernetes.io/name: slsa-demo-releaseplan
    app.kubernetes.io/component: release-plan
    app.kubernetes.io/part-of: slsa-konflux
    release.appstudio.openshift.io/application: slsa-demo-app
  annotations:
    release.appstudio.openshift.io/description: "SLSA-compliant release plan for demo application"
    release.appstudio.openshift.io/auto-release: "true"
    konflux.dev/slsa-level: "3"
spec:
  application: slsa-demo-app
  target: managed-namespace
  
  # Release strategy configuration
  releaseGracePeriodDays: 7
  
  # SLSA and VSA configuration
  data:
    slsa:
      # SLSA compliance level required
      level: "3"
      
      # Source verification requirements
      source:
        verification: "required"
        provenance: "slsa-source-verification"
      
      # Build verification requirements  
      build:
        verification: "required"
        provenance: "tekton-chains"
        hermeticity: "isolated"
      
      # VSA generation configuration
      vsa:
        enabled: true
        signingKey: "vsa-primary-key"
        verifierId: "https://managed.konflux.example.com/vsa-signer"
        transparencyLog: "https://rekor.sigstore.dev"
    
    # Policy evaluation configuration
    policy:
      # Policy bundles to evaluate
      bundles:
        - uri: "oci://quay.io/enterprise-contract/ec-policy-data:latest"
          name: "enterprise-contract-slsa3"
        - uri: "oci://quay.io/konflux/slsa-source-policy:latest"
          name: "slsa-source-verification"
      
      # Evaluation requirements
      evaluation:
        strict: true
        requiredLevels: ["SLSA_BUILD_LEVEL_3"]
        failureAction: "block"
    
    # Publication configuration
    publication:
      registry: "quay.io/konflux-slsa-example"
      namespace: "production"
      promotion:
        strategy: "copy"
        preserveDigests: true
        signImages: true
    
    # Attestation publishing configuration  
    attestations:
      publish: true
      registry: "quay.io/konflux-slsa-example/attestations"
      formats: ["vsa", "slsa-provenance", "sbom"]
      
  # Pipeline configuration passed to managed context
  pipeline:
    # Pipeline bundle reference (will be overridden by ReleasePlanAdmission)
    pipelineRef:
      resolver: "bundles"
      params:
        - name: "bundle"
          value: "quay.io/konflux-ci/tekton-catalog/pipeline-slsa-managed:latest"
        - name: "name"
          value: "slsa-managed-pipeline"
    
    # Service account for pipeline execution
    serviceAccountName: "managed-pipeline-sa"
    
    # Timeouts for pipeline execution
    timeouts:
      pipeline: "60m"
      tasks: "45m"
      finally: "15m"

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  generateName: slsa-demo-release-
  namespace: tenant-namespace
  labels:
    app.kubernetes.io/name: slsa-demo-release
    app.kubernetes.io/component: release
    app.kubernetes.io/part-of: slsa-konflux
    release.appstudio.openshift.io/application: slsa-demo-app
    release.appstudio.openshift.io/releaseplan: slsa-demo-releaseplan
  annotations:
    release.appstudio.openshift.io/description: "SLSA demo application release triggered by snapshot"
spec:
  # ReleasePlan reference
  releasePlan: slsa-demo-releaseplan
  
  # Snapshot reference (this would be set by the actual snapshot)
  # snapshot: slsa-demo-app-snapshot-abc123
  
  # Release data (optional overrides)
  data:
    # Override policy evaluation settings for this release
    policy:
      evaluation:
        strict: false  # Allow warnings for demo
    
    # Additional metadata for this release
    metadata:
      releaseType: "demo"
      buildPipeline: "slsa-tenant-build-pipeline"
      triggeredBy: "snapshot-creation"