apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: slsa-demo-releaseplanadmission
  namespace: managed-namespace
  labels:
    app.kubernetes.io/name: slsa-demo-releaseplanadmission
    app.kubernetes.io/component: release-admission
    app.kubernetes.io/part-of: slsa-konflux
    release.appstudio.openshift.io/application: slsa-demo-app
  annotations:
    release.appstudio.openshift.io/description: "Admission control for SLSA demo releases"
    konflux.dev/managed-context: "true"
    konflux.dev/slsa-level: "3"
spec:
  # Applications that this admission applies to
  applications:
    - slsa-demo-app
  
  # Origin namespace (where releases come from)
  origin: tenant-namespace
  
  # Policy configuration for admission control
  policy: "enterprise-contract-slsa3"
  
  # Pipeline configuration for release processing
  pipeline:
    # Reference to our managed pipeline
    pipelineRef:
      name: slsa-managed-pipeline
      resolver: "git"
      params:
        - name: "url"
          value: "https://github.com/konflux-slsa/slsa-konflux-example"
        - name: "revision"
          value: "main"
        - name: "pathInRepo"
          value: "managed-context/pipelines/slsa-managed-pipeline/0.1/slsa-managed-pipeline.yaml"
    
    # Service account for pipeline execution in managed namespace
    serviceAccountName: "managed-pipeline-sa"
    
    # Timeout configuration
    timeouts:
      pipeline: "60m"
      tasks: "45m"
      finally: "15m"
  
  # Data configuration for the managed pipeline
  data:
    # SLSA configuration
    slsa:
      # Verification requirements
      verification:
        strict: true
        requiredAttestations: ["buildProvenance", "sbom", "sourceVerification"]
        policyBundles: 
          - "oci://quay.io/enterprise-contract/ec-policy-data:latest"
          - "oci://quay.io/konflux/slsa-source-policy:latest"
      
      # VSA generation settings
      vsa:
        enabled: true
        signingKey: "vsa-primary-key"
        verifierId: "https://managed.konflux.example.com/vsa-signer"
        verifierVersion: "v1.0.0"
        outputFormat: "slsa-vsa-v1"
        attachToImage: true
    
    # Conforma policy evaluation configuration
    conforma:
      # Policy bundle configuration
      policyBundle: 
        uri: "oci://quay.io/enterprise-contract/ec-policy-data:latest"
        digest: ""  # Will be resolved at runtime
      
      # Evaluation settings
      evaluation:
        strictMode: false  # Allow warnings for demo
        timeoutMinutes: 10
        includeAttestations: true
        
      # VSA payload configuration  
      vsa:
        includePolicy: true
        includeDependencies: true
        includeInputAttestations: true
    
    # Image promotion configuration
    promotion:
      # Target registry for promoted images
      registry: "quay.io/konflux-slsa-example"
      namespace: "production"
      
      # Promotion strategy
      strategy: "copy"
      preserveDigests: true
      signPromotedImages: true
      
      # Attestation handling
      copyAttestations: true
      generatePromotionAttestation: true
    
    # Publication configuration
    publication:
      # Registry for attestation publishing
      attestationRegistry: "quay.io/konflux-slsa-example/attestations"
      
      # VSA publishing
      vsa:
        publish: true
        registry: "quay.io/konflux-slsa-example/vsa"
        format: "oci-artifact"
        
      # Transparency log integration
      transparencyLog:
        enabled: true
        url: "https://rekor.sigstore.dev"
        
    # Notification configuration
    notifications:
      # Release completion notifications
      webhook:
        enabled: false
        url: ""
      
      # Failure notifications  
      failure:
        notify: true
        channels: ["log"]

---
# Example of a manual Release for testing
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  generateName: manual-slsa-demo-release-
  namespace: tenant-namespace
  labels:
    app.kubernetes.io/name: manual-slsa-demo-release
    app.kubernetes.io/component: release
    app.kubernetes.io/part-of: slsa-konflux
    release.appstudio.openshift.io/application: slsa-demo-app
    release.appstudio.openshift.io/releaseplan: slsa-demo-releaseplan
    release.appstudio.openshift.io/manual: "true"
  annotations:
    release.appstudio.openshift.io/description: "Manual SLSA demo release for testing"
spec:
  # ReleasePlan reference
  releasePlan: slsa-demo-releaseplan
  
  # Snapshot reference (must be updated with actual snapshot name)
  # This would typically be set by automation or manual trigger
  snapshot: "slsa-demo-app-snapshot-latest"
  
  # Override data for manual testing
  data:
    # Test configuration overrides
    testing:
      manual: true
      skipValidation: false
      
    # Policy evaluation overrides for testing
    policy:
      evaluation:
        strict: false  # Allow policy warnings for demo
        
    # Image configuration for testing
    images:
      # This would be populated with actual snapshot data
      - name: "slsa-demo-app"
        repository: "quay.io/konflux-slsa-example/go-app"
        tag: "latest"