apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.release.serviceAccount }}
  namespace: {{ .Values.release.targetNamespace }}
secrets:
{{- if and .Values.release.trustedArtifacts.username .Values.release.trustedArtifacts.password }}
  - name: trusted-artifacts-secret
{{- else }}
  - name: regcred-internal-registry
{{- end }}
