apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}
spec:
  displayName: {{ .Values.displayName | default .Values.applicationName }}
