{{- if and .Values.requiresClusterAdmin .Values.users }}
{{- range .Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ . }}-self-access-review
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konflux-self-access-reviewer
subjects:
- kind: User
  name: {{ . }}@konflux.dev
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
