---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: policy-pr
  namespace: {{ .Values.namespace }}
spec:
  application: {{ .Values.applicationName }}
  contexts:
    - name: pull_request
      description: "PR source branches are not protected"
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/konflux-ci/build-definitions
      - name: revision
        value: renovate/ec
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
  params:
    - name: POLICY_CONFIGURATION
      value: {{ .Values.release.targetNamespace }}/{{ .Values.release.policyName }}
    - name: PUBLIC_KEY
      value: k8s://tekton-pipelines/public-key
    - name: STRICT
      value: "true"
    - name: EXTRA_RULE_DATA
      value: "slsa_source_min_level=1"
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: policy-push
  namespace: {{ .Values.namespace }}
spec:
  application: {{ .Values.applicationName }}
  contexts:
    - name: push
      description: "Validate push builds with strict policy (matches release requirements)"
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/konflux-ci/build-definitions
      - name: revision
        value: renovate/ec
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
  params:
    - name: POLICY_CONFIGURATION
      value: {{ .Values.release.targetNamespace }}/{{ .Values.release.policyName }}
    - name: PUBLIC_KEY
      value: k8s://tekton-pipelines/public-key
    - name: STRICT
      value: "true"
