apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: policy
  namespace: {{ .Values.namespace }}
spec:
  application: {{ .Values.applicationName }}
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/konflux-ci/build-definitions
      - name: revision
        value: renovate/ec
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
  params:
    - name: POLICY_CONFIGURATION
      value: {{ .Values.release.targetNamespace }}/{{ .Values.release.policyName }}
    - name: PUBLIC_KEY
      value: k8s://tekton-pipelines/public-key
    - name: STRICT
      value: "true"
