{{- $destination := .Values.release.destination | default (printf "registry-service.kind-registry/released-%s" .Values.applicationName) }}
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: {{ .Values.applicationName }}-release-admission
  namespace: {{ .Values.release.targetNamespace }}
spec:
  applications:
    - {{ .Values.applicationName }}
  origin: {{ .Values.namespace }}
  environment: {{ .Values.release.environment }}
  policy: {{ .Values.release.policyName }}
  pipeline:
    serviceAccountName: {{ .Values.release.serviceAccount }}
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/arewm/slsa-konflux-example
        - name: revision
          value: main
        - name: pathInRepo
          value: managed-context/pipelines/slsa-e2e-release/slsa-e2e-release.yaml
  data:
    mapping:
      components:
        - name: {{ .Values.applicationName }}
          repository: {{ $destination }}
