{{- $destination := .Values.release.destination | default (printf "registry-service.kind-registry/released-%s" .Values.applicationName) }}
{{- $pipelineUrl := .Values.release.pipeline.url | default .Values.repositoryUrl }}
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: {{ .Values.applicationName }}-release-admission
  namespace: {{ .Values.release.targetNamespace }}
spec:
  applications:
    - {{ .Values.applicationName }}
  origin: {{ .Values.namespace }}
  environment: {{ .Values.release.environment }}
  policy: {{ .Values.release.policyName }}
  pipeline:
    serviceAccountName: {{ .Values.release.serviceAccount }}
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: {{ $pipelineUrl }}
        - name: revision
          value: {{ .Values.release.pipeline.revision }}
        - name: pathInRepo
          value: {{ .Values.release.pipeline.pathInRepo }}
  data:
    mapping:
      components:
        - name: {{ .Values.applicationName }}
          repository: {{ $destination }}
