{{- if .Values.signing.enableSigning }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: signing-key-generator
  namespace: {{ .Values.release.targetNamespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: signing-key-generator
subjects:
- kind: ServiceAccount
  name: signing-key-generator
  namespace: {{ .Values.release.targetNamespace }}
{{- end }}
